---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-service
spec:
  chart:
    spec:
      chart: podinfo
      version: latest
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  values:
    image:
      repository: riteshve/podinfo
      tag: latest-20250621130825
      pullPolicy: IfNotPresent
    ui:
      color: "#532864"
      message: "Hello, I am podinfo version latest-20250621130825."
  install:
    createNamespace: true
  uninstall:
    keepHistory: false
  interval: 10m
