---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sources-helm-repository-podinfo
  namespace: podinfo
  labels:
    podinfo.namespace: podinfo
spec:
  interval: 5m0s
  path: ./sources/helm-repository
  prune: true
  sourceRef:
    kind: GitRepository
    name: deploy-with-gitops
    namespace: flux-system